apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: wil42/playground:v1
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
